CRUD/CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

CRUD/first_app/urls.py
from django.urls import path
from django.conf.urls import url
from first_app import views

app_name = "first_app"

urlpatterns = [

    path('', views.index, name="index"),
    path('student_form/', views.student_form, name="student_form"),
    path('student_info/<int:student_id>/', views.student_info, name="student_info"),
    path('student_update/<int:student_id>/', views.student_update, name="student_update"),
    path('student_delete/<int:student_id>/', views.student_delete, name="student_delete"),


]

CRUD/first_app/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()

    def __str__(self):
        return str(self.pk) + ' ' + self.first_name + " " + self.last_name

CRUD/first_app/forms.py
from django import forms
from first_app import models


class StudentForm(forms.ModelForm):
    class Meta:
        model = models.Student  # from_models.py _class
        fields = "__all__"

CRUD/first_app/views.py
from django.shortcuts import render
from first_app import forms
from first_app.models import Student


# Create your views here.

def index(request):
    student_list = Student.objects.order_by('first_name')
    dictionary = {'title': "Index", 'student_list': student_list}
    return render(request, 'first_app/index.html', context=dictionary)


def student_form(request):
    form = forms.StudentForm  # from_forms.py_class

    if request.method == "POST":
        form = forms.StudentForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
    dictionary = {'title': "Student Form", 'student_form': form}  # form_shows_in_student_form
    return render(request, 'first_app/student_form.html', context=dictionary)


def student_info(request, student_id):
    student_info = Student.objects.get(pk=student_id)
    dictionary = {'student_info': student_info}
    return render(request, 'first_app/student_info.html', context=dictionary)


def student_update(request, student_id):
    student_info = Student.objects.get(pk=student_id)
    form = forms.StudentForm(instance=student_info)  # for update student info

    if request.method == "POST":
        form = forms.StudentForm(request.POST, instance=student_info)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
    dictionary = {'student_form': form}
    return render(request, 'first_app/student_update.html', context=dictionary)


def student_delete(request, student_id):
    student = Student.objects.get(pk=student_id).delete()
    dictionary = {'delete_message': "Successfully Delete"}
    return render(request, 'first_app/student_delete.html', context=dictionary)

CRUD/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'first_app:index' %}">Index</a>
        </li>
        <li class="nav-item">
             <a class="nav-link" href="{% url 'first_app:student_form' %}">Student Form</a>
        </li>
    </ul>



    {% block body_block %}


    {% endblock %}
</body>
</html>

CRUD/templates/first_app/index.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h1>INDEX</h1>
<h2>Student_list</h2>

<ul>
{% if student_list %}

{% for student in student_list %} <!-- student means value here -->

    <li>
        <a href= "{% url 'first_app:student_info' student_id=student.id %}" > {{student.first_name}} {{student.last_name}} </a>
    </li>
{% endfor %}


{% else %}

    <li>
        <h3> No student </h3>
    </li>

{% endif %}


</ul>

{% endblock %}

CRUD/templates/first_app/student_delete.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<div class = "alert alert-danger"> {{delete_message}} </div>


{% endblock %}

CRUD/templates/first_app/student_form.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h1>Student Form</h1>

<form action=" " method="POST">
    {{ student_form.as_p }}
    {% csrf_token %}

    <input type="submit" name="SUBMIT" value="Add Student">
</form>

{% endblock %}

CRUD/templates/first_app/student_info.html
{% extends 'first_app/base.html' %}

{% block body_block %}






<h1>Student Info</h1>

<h3>Student Id: {{ student_info.id }} </h3>
<h3>Student Name: {{student_info.first_name}}{{student_info.last_name}}</h3>
<h3>Email: {{student_info.email}}</h3>
<h3>Phone: {{student_info.phone}}</h3>

<a href= "{% url 'first_app:student_update' student_id=student_info.id%}" class="btn btn-primary">Update</a>
<a href= "{% url 'first_app:student_delete' student_id=student_info.id%}" class="btn btn-primary">Delete</a>
{% endblock %}

CRUD/templates/first_app/student_update.html
{% extends 'first_app/base.html' %}

{% block body_block %}

<h1>Student Update</h1>



<form action=" " method="POST">
    {{ student_form.as_p }}
    {% csrf_token %}

    <input type="submit" value="update">
</form>

{% endblock body_block %}